/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlanId = IDL.Nat;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AspectRatio = IDL.Variant({
  'square' : IDL.Null,
  'portrait' : IDL.Null,
  'landscape' : IDL.Null,
});
export const GenerateOptions = IDL.Record({
  'subtitlesEnabled' : IDL.Bool,
  'maxClipSeconds' : IDL.Nat,
  'aspectRatio' : AspectRatio,
});
export const GeneratePlanRequest = IDL.Record({
  'url' : IDL.Text,
  'options' : GenerateOptions,
});
export const Clip = IDL.Record({
  'endSeconds' : IDL.Nat,
  'title' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'caption' : IDL.Text,
  'index' : IDL.Nat,
  'startSeconds' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const ClipPlan = IDL.Record({
  'id' : PlanId,
  'owner' : IDL.Principal,
  'sourceTitle' : IDL.Text,
  'clips' : IDL.Vec(Clip),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'subtitlesEnabled' : IDL.Bool,
  'sourceUrl' : IDL.Text,
  'language' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'maxClipSeconds' : IDL.Nat,
  'channel' : IDL.Text,
  'aspectRatio' : AspectRatio,
});
export const PlanError = IDL.Variant({
  'aiFailure' : IDL.Text,
  'unreachable' : IDL.Text,
  'invalidUrl' : IDL.Text,
  'noCaptions' : IDL.Text,
});
export const GeneratePlanResult = IDL.Variant({
  'ok' : ClipPlan,
  'err' : PlanError,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePlan' : IDL.Func([PlanId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'generatePlan' : IDL.Func([GeneratePlanRequest], [GeneratePlanResult], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlan' : IDL.Func([PlanId], [IDL.Opt(ClipPlan)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPlans' : IDL.Func([], [IDL.Vec(ClipPlan)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlanId = IDL.Nat;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AspectRatio = IDL.Variant({
    'square' : IDL.Null,
    'portrait' : IDL.Null,
    'landscape' : IDL.Null,
  });
  const GenerateOptions = IDL.Record({
    'subtitlesEnabled' : IDL.Bool,
    'maxClipSeconds' : IDL.Nat,
    'aspectRatio' : AspectRatio,
  });
  const GeneratePlanRequest = IDL.Record({
    'url' : IDL.Text,
    'options' : GenerateOptions,
  });
  const Clip = IDL.Record({
    'endSeconds' : IDL.Nat,
    'title' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'caption' : IDL.Text,
    'index' : IDL.Nat,
    'startSeconds' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const ClipPlan = IDL.Record({
    'id' : PlanId,
    'owner' : IDL.Principal,
    'sourceTitle' : IDL.Text,
    'clips' : IDL.Vec(Clip),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'subtitlesEnabled' : IDL.Bool,
    'sourceUrl' : IDL.Text,
    'language' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'maxClipSeconds' : IDL.Nat,
    'channel' : IDL.Text,
    'aspectRatio' : AspectRatio,
  });
  const PlanError = IDL.Variant({
    'aiFailure' : IDL.Text,
    'unreachable' : IDL.Text,
    'invalidUrl' : IDL.Text,
    'noCaptions' : IDL.Text,
  });
  const GeneratePlanResult = IDL.Variant({
    'ok' : ClipPlan,
    'err' : PlanError,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePlan' : IDL.Func([PlanId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'generatePlan' : IDL.Func([GeneratePlanRequest], [GeneratePlanResult], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlan' : IDL.Func([PlanId], [IDL.Opt(ClipPlan)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPlans' : IDL.Func([], [IDL.Vec(ClipPlan)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };