/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AspectRatio = { 'square' : null } |
  { 'portrait' : null } |
  { 'landscape' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Clip {
  'endSeconds' : bigint,
  'title' : string,
  'hashtags' : Array<string>,
  'caption' : string,
  'index' : bigint,
  'startSeconds' : bigint,
}
export interface ClipPlan {
  'id' : PlanId,
  'owner' : Principal,
  'sourceTitle' : string,
  'clips' : Array<Clip>,
  'name' : string,
  'createdAt' : Timestamp,
  'subtitlesEnabled' : boolean,
  'sourceUrl' : string,
  'language' : string,
  'durationSeconds' : bigint,
  'maxClipSeconds' : bigint,
  'channel' : string,
  'aspectRatio' : AspectRatio,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface GenerateOptions {
  'subtitlesEnabled' : boolean,
  'maxClipSeconds' : bigint,
  'aspectRatio' : AspectRatio,
}
export interface GeneratePlanRequest {
  'url' : string,
  'options' : GenerateOptions,
}
export type GeneratePlanResult = { 'ok' : ClipPlan } |
  { 'err' : PlanError };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type PlanError = { 'aiFailure' : string } |
  { 'unreachable' : string } |
  { 'invalidUrl' : string } |
  { 'noCaptions' : string };
export type PlanId = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePlan' : ActorMethod<[PlanId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'generatePlan' : ActorMethod<[GeneratePlanRequest], GeneratePlanResult>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlan' : ActorMethod<[PlanId], [] | [ClipPlan]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPlans' : ActorMethod<[], Array<ClipPlan>>,
  'schema' : ActorMethod<[], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];