/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface Clip {
    endSeconds: bigint;
    title: string;
    hashtags: Array<string>;
    caption: string;
    index: bigint;
    startSeconds: bigint;
}
export interface ClipPlan {
    id: PlanId;
    owner: Principal;
    sourceTitle: string;
    clips: Array<Clip>;
    name: string;
    createdAt: Timestamp;
    subtitlesEnabled: boolean;
    sourceUrl: string;
    language: string;
    durationSeconds: bigint;
    maxClipSeconds: bigint;
    channel: string;
    aspectRatio: AspectRatio;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface GenerateOptions {
    subtitlesEnabled: boolean;
    maxClipSeconds: bigint;
    aspectRatio: AspectRatio;
}
export interface GeneratePlanRequest {
    url: string;
    options: GenerateOptions;
}
export type GeneratePlanResult = {
    __kind__: "ok";
    ok: ClipPlan;
} | {
    __kind__: "err";
    err: PlanError;
};
export interface HttpHeader {
    value: string;
    name: string;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export type PlanError = {
    __kind__: "aiFailure";
    aiFailure: string;
} | {
    __kind__: "unreachable";
    unreachable: string;
} | {
    __kind__: "invalidUrl";
    invalidUrl: string;
} | {
    __kind__: "noCaptions";
    noCaptions: string;
};
export type PlanId = bigint;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Timestamp = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum AspectRatio {
    square = "square",
    portrait = "portrait",
    landscape = "landscape"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deletePlan(id: PlanId): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    generatePlan(request: GeneratePlanRequest): Promise<GeneratePlanResult>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getPlan(id: PlanId): Promise<ClipPlan | null>;
    isCallerAdmin(): Promise<boolean>;
    listPlans(): Promise<Array<ClipPlan>>;
    schema(): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AspectRatio as _AspectRatio, Cell as _Cell, Clip as _Clip, ClipPlan as _ClipPlan, Error as _Error, GenerateOptions as _GenerateOptions, GeneratePlanRequest as _GeneratePlanRequest, GeneratePlanResult as _GeneratePlanResult, PlanError as _PlanError, PlanId as _PlanId, Result as _Result, Result__1 as _Result__1, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deletePlan(arg0: PlanId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlan(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async generatePlan(arg0: GeneratePlanRequest): Promise<GeneratePlanResult> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePlan(to_candid_GeneratePlanRequest_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GeneratePlanResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePlan(to_candid_GeneratePlanRequest_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GeneratePlanResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlan(arg0: PlanId): Promise<ClipPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlan(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlan(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listPlans(): Promise<Array<ClipPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlans();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlans();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_AspectRatio_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AspectRatio): AspectRatio {
    return "square" in value ? AspectRatio.square : "portrait" in value ? AspectRatio.portrait : "landscape" in value ? AspectRatio.landscape : value;
}
function from_candid_Cell_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ClipPlan_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClipPlan): ClipPlan {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_GeneratePlanResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GeneratePlanResult): GeneratePlanResult {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PlanError_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanError): PlanError {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClipPlan]): ClipPlan | null {
    return value.length === 0 ? null : from_candid_ClipPlan_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n12(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlanId;
    owner: Principal;
    sourceTitle: string;
    clips: Array<_Clip>;
    name: string;
    createdAt: _Timestamp;
    subtitlesEnabled: boolean;
    sourceUrl: string;
    language: string;
    durationSeconds: bigint;
    maxClipSeconds: bigint;
    channel: string;
    aspectRatio: _AspectRatio;
}): {
    id: PlanId;
    owner: Principal;
    sourceTitle: string;
    clips: Array<Clip>;
    name: string;
    createdAt: Timestamp;
    subtitlesEnabled: boolean;
    sourceUrl: string;
    language: string;
    durationSeconds: bigint;
    maxClipSeconds: bigint;
    channel: string;
    aspectRatio: AspectRatio;
} {
    return {
        id: value.id,
        owner: value.owner,
        sourceTitle: value.sourceTitle,
        clips: value.clips,
        name: value.name,
        createdAt: value.createdAt,
        subtitlesEnabled: value.subtitlesEnabled,
        sourceUrl: value.sourceUrl,
        language: value.language,
        durationSeconds: value.durationSeconds,
        maxClipSeconds: value.maxClipSeconds,
        channel: value.channel,
        aspectRatio: from_candid_AspectRatio_n23(_uploadFile, _downloadFile, value.aspectRatio)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n8(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ClipPlan;
} | {
    err: _PlanError;
}): {
    __kind__: "ok";
    ok: ClipPlan;
} | {
    __kind__: "err";
    err: PlanError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ClipPlan_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_PlanError_n24(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aiFailure: string;
} | {
    unreachable: string;
} | {
    invalidUrl: string;
} | {
    noCaptions: string;
}): {
    __kind__: "aiFailure";
    aiFailure: string;
} | {
    __kind__: "unreachable";
    unreachable: string;
} | {
    __kind__: "invalidUrl";
    invalidUrl: string;
} | {
    __kind__: "noCaptions";
    noCaptions: string;
} {
    return "aiFailure" in value ? {
        __kind__: "aiFailure",
        aiFailure: value.aiFailure
    } : "unreachable" in value ? {
        __kind__: "unreachable",
        unreachable: value.unreachable
    } : "invalidUrl" in value ? {
        __kind__: "invalidUrl",
        invalidUrl: value.invalidUrl
    } : "noCaptions" in value ? {
        __kind__: "noCaptions",
        noCaptions: value.noCaptions
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClipPlan>): Array<ClipPlan> {
    return value.map((x)=>from_candid_ClipPlan_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AspectRatio_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AspectRatio): _AspectRatio {
    return value == AspectRatio.square ? {
        square: null
    } : value == AspectRatio.portrait ? {
        portrait: null
    } : value == AspectRatio.landscape ? {
        landscape: null
    } : value;
}
function to_candid_GenerateOptions_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenerateOptions): _GenerateOptions {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_GeneratePlanRequest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GeneratePlanRequest): _GeneratePlanRequest {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    options: GenerateOptions;
}): {
    url: string;
    options: _GenerateOptions;
} {
    return {
        url: value.url,
        options: to_candid_GenerateOptions_n16(_uploadFile, _downloadFile, value.options)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subtitlesEnabled: boolean;
    maxClipSeconds: bigint;
    aspectRatio: AspectRatio;
}): {
    subtitlesEnabled: boolean;
    maxClipSeconds: bigint;
    aspectRatio: _AspectRatio;
} {
    return {
        subtitlesEnabled: value.subtitlesEnabled,
        maxClipSeconds: value.maxClipSeconds,
        aspectRatio: to_candid_AspectRatio_n18(_uploadFile, _downloadFile, value.aspectRatio)
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
